### ISSUE TITLE
Dokumentation der BIOS-Problematik

### ISSUE THREAD

**Issue by BenediktSt** [AtosReferenzApplikation/docker-container#38]
Im Bereich der Häufig auftretenden Probleme im Wiki auch die BIOS-Problematik mit aufnehmen

**Comment by BenediktSt** [comment]
@MarvinK97 @olniklas könntet ihr hier den Wiki-Artikel verlinken, in dem das festgehalten wurde?

**Comment by MarvinK97** [comment]
Zum [Requirements](https://github.com/AtosReferenzApplikation/docker-container/wiki/Requirements#voraussetzung) Artikel hinzugefügt.
