### ISSUE TITLE
#49- Aufsetzen von Protractor Testfällen

### ISSUE THREAD

**Issue by BenediktSt** [AtosReferenzApplikation/docker-container#49]
# Beschreibung
Als Entwickler und Tester der Referenzapplikation möchte ich, dass die Funktionalität der einzelnen Komponenten zusammen und integriert getestet werden können, um mir bei der Weiterentwicklung sicher sein zu können, dass sich keine Fehler in bereits bestehende Funktionen der Anwendung einschleichen.

# Akzeptanzkriterien
- Im Code der Referenzapplikation ist eine Konfiguration zur Ausführung der Tests vorhanden
- Es existieren e2e-Tests, welche die Funktion der Feedback-Komponente über den Browser sicherstellen

**Comment by Ferias** [comment]
Testfälle nicht im Ordner Protractor ausführen, sonst funktionieren sie nicht.
