### ISSUE TITLE
Erweiterung des Tokenizings

### ISSUE THREAD

**Issue by BenediktSt** [AtosReferenzApplikation/docker-container#53]
# Beschreibung
Als Analyst des Benutzerfeedbacks möchte ich die Kundeninhalte möglichst effizient auswerten können. Dabei sollen worte in unterschiedlichen Deklinationen/Konjugationen und dem gleichen Wortstamm zusammengefasst werden.

Mögliche Stemmer für den Einsatz:
- Hunspell Stemmer
- Snowball Stemmer
- Oder gerne auch andere

(Wenn ich es richtig verstehe, kann dafür jede Library für Python eingesetzt werden)

# Akzeptanzkriterien
- Der analysierte Text wird in eine Reihe von Tokes umgewandelt
- Aus diesen Token werden alle Stopworte entfernt, da diese keinen Inhaltlichen Mehrwert liefern
- Für die Lemmatisierung wird ein Tool eingesetzt, welche möglichst viele verschiedene Formen von Worten auf einen gemeinsamen Stamm vereint
- Es wird festgehalten, wie häufig ein Token in dem Ausgangstext vorkommt 
- Es wurde dokumentiert, welche Verfahren einen Mehrwert brachten
- Es wurde dokumentiert, welche Verfahren keinen Mehrwert brachten und warum diese Verworfen wurden

**Comment by LeaKleemann** [comment]
https://github.com/AtosReferenzApplikation/docker-container/wiki/Textvorverarbeitung-%28Spark%29

**Comment by LeaKleemann** [comment]
https://github.com/AtosReferenzApplikation/docker-container/wiki/Textvorverarbeitung-mit-SparkNLP

**Comment by LeaKleemann** [comment]
https://github.com/AtosReferenzApplikation/docker-container/wiki/Textvorverarbeitung-NLTK
