### ISSUE TITLE
Clusteranalyse des Inputs

### ISSUE THREAD

**Issue by BenediktSt** [AtosReferenzApplikation/docker-container#54]
# Beschreibung
Als Analyst des Benutzerfeedbacks möchte ich herausfinden, welche Nachrichten sich mit ähnlichen Inhalten beschäftigen. Dabei möchte ich aus allen verfügbaren Dokumenten Cluster auf basis der existierenden und nahe beieinander liegenden Algorithmen bilden.

Mögliche Ansätze:
- K-Means
- Latent Dirichlet allocation (LDA)
- gerne auch alternative

# Akzeptanzkriterien
- Es existieren (Demo-) Daten für mehrere Dokumente, welche für die weitere Analyse verwendet werden können
  - Hier kann für eine unabhängige Arbeit von dem Beriech des Tokenizings eine andere Datenbasis verwendet werden
- Die Dateien werden anhand ihrer Eigenschaften in Cluster gruppiert
  - Die Eigenschaften eines Dokuments sind die  vorkommenden Worte und deren Anzahl
- Aus den Clustern lässt sich ermitteln, welche Eigenschaften (Worte) die gruppierten Dokumente gemeinsam haben

**Comment by LeaKleemann** [comment]
https://github.com/AtosReferenzApplikation/docker-container/wiki/Topic-Extraction-mit-Apache-Spark

**Comment by LeaKleemann** [comment]
https://github.com/AtosReferenzApplikation/feedback-data-analyzer/blob/lea/ver2.py

**Comment by Mlorenz12** [comment]
https://github.com/AtosReferenzApplikation/feedback-data-analyzer/blob/miriam/Topic_Extraction/Clustering.py

**Comment by Mlorenz12** [comment]
https://github.com/AtosReferenzApplikation/docker-container/wiki/Clustering:-K-Means
https://github.com/AtosReferenzApplikation/docker-container/wiki/Clustering:-LDA

**Comment by LeaKleemann** [comment]
https://github.com/AtosReferenzApplikation/feedback-data-analyzer/blob/lea/TopicExtraction/TopicExtraction.py
