### ISSUE TITLE
Trainingsdaten via E2E-Tests anlegen

### ISSUE THREAD

**Issue by olniklas** [AtosReferenzApplikation/docker-container#56]
# Beschreibung
Für die Textanalyse benötigen wir Trainingsdaten für die Sentinent-Analyse (Empfindung)
D. h. Daten deren "Empfindung" bereits voranalysiert wurde sollen in der GUI-erfasst werden. 
Sie sollen als Sollwerte dienen für die im Projekt entwickelten Analysetechniken. 
Es existieren IMDB (Movie-Database-Reviews) und Tweets, im Netz, die bereits voranalysiert sind. 
Diese gilt es als Trainingsdatenbestand über die Gui zu erfassen. 

- [x] Datenquellen bitte liefern. 

# Akzeptanzkriterien 
- Wartbarkeite bei Änderungen im Trainingsdatenbestand.
- Möglichkeit andere Trainingsdatenbestände einzulesen (per Datei: csv)
- Protractor-Tests müssen die Trainings-Datenbestände entgegennehmen 
- Lösungskonzept für Datadriven testing mit Protractor.

**Comment by BenediktSt** [comment]
Also hier mögliche Datenquellen:
* http://ai.stanford.edu/~amaas/data/sentiment/
* https://www.spinningbytes.com/resources/germansentiment/
* https://www.kaggle.com/rtatman/german-sentiment-analysis-toolkit

Ich würde im ersten Schritt auch Dateien zum einlesen der Daten nehmen. Da bietet sich, so wie ich das sehe CSV an.

Wenn ihr noch weitere Testdatensammlungen findet, welche beispielsweise auch schon Trainingsdaten zu Topic Extractions haben, dann könnt ihr die auch gerne nehmen.

**Comment by BenediktSt** [comment]
Pull Request #75 erst abschließen
