### ISSUE TITLE
Ausgabe der wichtigsten Worte für ein Dokument

### ISSUE THREAD

**Issue by BenediktSt** [AtosReferenzApplikation/docker-container#58]
# Beschreibung
Als Analyst würde ich für ein Dokument gerne sehen, welches die wichtigsten Worte für dieses sind. Dabei sollen die Ergebnisse in einer Form aufbereitet werden, in welcher die wichtigen Worte schnell und einfach zu erfassen sind.

# Akzeptanzkriterien
* Für ein Dokument lässt sich darstellen, was die wichtigen Worte für dieses Dokument sind
* Ein Wort ist für diesen Fall wichtig, wenn es häufig in dem Dokument vorkommt
* Es wird definiert, wie viele der wichtigen Worte angezeigt werden
* Die Anzeige kann dabei noch rudimentär aussehen, z.B Ausgabe per Console

**Comment by LeaKleemann** [comment]
https://github.com/AtosReferenzApplikation/feedback-data-analyzer/blob/lea/singleDocumentWordCloud.py

**Comment by Mlorenz12** [comment]
https://github.com/AtosReferenzApplikation/docker-container/wiki/Spark:-Visualisierungen
