### ISSUE TITLE
Generieren von aussagekräftigen Testdaten

### ISSUE THREAD

**Issue by BenediktSt** [AtosReferenzApplikation/docker-container#61]
# Beschreibung
Als Data Scientist möchte ich in der Lage sein, meine Umsetzung der Clusterbildung anhand einer sinnvollen Testdatenmenge zu beurteilen. Dabei sollen die Testdaten so aufgebaut sein, dass sich daraus logisch Cluster bilden lassen. Diese identifizierten Cluster sollen im Anschluss dazu dienen einzuschätzen, ob ein Algorithmus eine gute Clusterung vornehmen konnte.

# Akzeptanzkriterien
* Es existiert eine Testdatenmenge mit mehreren Dokumenten
* Die einzelnen Worte lassen sich manuell durch Betrachtung auf Basis der vorkommenden Worte in einzelne Cluster gruppieren

**Comment by Mlorenz12** [comment]
https://github.com/AtosReferenzApplikation/feedback-data-analyzer/tree/miriam/Testdaten
