### ISSUE TITLE
Messung der Clusterungsqualität

### ISSUE THREAD

**Issue by BenediktSt** [AtosReferenzApplikation/docker-container#62]
# Beschreibung
Als Data Scientist möchte ich in der Lage sein, die Qualität der Clusterung durch einen Algorithmus zu messen. Dabei können zwei Faktoren bei der Messung betrachtet werden.
* Wie stark stimmen die Dokumente in einem gemeinsamen Cluster überein / wie nahe sind diese zusammen?
* Wie trennscharf sind die Cluster voneinander abgetrennt / wie weit sind diese voneinander entfernt?
* Auch noch ganz andere Alternativen durch Spark sind möglich

# Akzeptanzkriterien
* Es kann eine Kennzahl ermittelt werden, welche eine Aussage über die Clusterqualität gibt
* Diese Kennzahl kann theoretisch weiterverwendet werden, um die Clusteralgorithmen zu optimieren

**Comment by Mlorenz12** [comment]
https://github.com/AtosReferenzApplikation/docker-container/wiki/Clustering:-K-Means

Da ich kein K-Means mehr durchführen kann, bin ich mir nicht sicher, ob der Code noch funktioniert (musste etwas ändern)
