### ISSUE TITLE
## Circuit Demo App

### ISSUE THREAD

**Issue by mtrenkle** [AtosReferenzApplikation/docker-container#63]
Eines der tollen Features an Circuit ist die offene API, mit der die Circuit-Funktionalität in eigene Anwendungen integriert werden kann. 
Ich möchte dem potentiellen Kunden BA dieses Feature nicht nur versprechen, sondern gleich in echt zeigen. Dazu soll es eine Demo App geben, mit der mögliche BA-Szenarien gezeigt werden können.

**Comment by BenediktSt** [comment]
+1

**Comment by BenediktSt** [comment]
related to #44
