### ISSUE TITLE
Anzeige der Top Themen als einfache Liste

### ISSUE THREAD

**Issue by BenediktSt** [AtosReferenzApplikation/docker-container#67]
# Beschreibung
Als Business Analyst möchte ich in der Lage sein, einfach und schnell erkennen zu können, was die Top Themen unseres Kundenfeedbacks ist. Dazu möchte ich eine Aufstellung an Themen welche nach Häufigkeit (absteigend) sortiert sind.

# Akzeptanzkriterien
* Es steht eine liste der Top Themen zur Verfügung
* Die Liste ist nach Häufigkeit absteigend sortiert
* Die Liste enthält nachvollziehbare Themen und Begriffe

**Comment by LeaKleemann** [comment]
https://github.com/AtosReferenzApplikation/feedback-data-analyzer/blob/lea/TopicExtraction/highestTopicDistribution.py
