### ISSUE TITLE
Sentiment Analye auf Basis eines dictionaries

### ISSUE THREAD

**Issue by BenediktSt** [AtosReferenzApplikation/docker-container#68]
# Beschreibung
Als Business Analyst möchte ich sehen, welche Stimmung innerhalb der Kundenfeedbacks vorherrscht, Dabei soll dies auf Basis eines dictionaries ermittelt werden, welches einzelne Worte auf deren positive oder negative Stimmung bewertet. Auf dieses Basis soll eine Gesamtstimmung für ein Dokument ermittelt werden.

# Akzeptanzkriterien
* Es wird ein englisches dictionary mit einer Bewertung nach Stimmung verwendet
* Für ein gesamtes Dokument kann eine Stimmung ermittelt werden

**Comment by LeaKleemann** [comment]
https://github.com/AtosReferenzApplikation/feedback-data-analyzer/tree/lea/SentimentAnalysis

**Comment by LeaKleemann** [comment]
https://github.com/AtosReferenzApplikation/docker-container/wiki/Spark%3A-Sentimentanalyse-mit-Dictionaries
