### ISSUE TITLE
Umbau des Spark Codes in eigenständig ausführbare Programme

### ISSUE THREAD

**Issue by BenediktSt** [AtosReferenzApplikation/docker-container#73]
# Beschreibung
Um langfristig die Analysen in Spark eigenständig ohne manuelles eingreifen auszuführen, ist ein erster Schritt, den bis jetzt erstellen Code eigenständig auszuführen. Dazu sollen die bisherigen Analysen durchgeführt werden, ohne dass dazu die pyspark shell genutzt wird.

# Akzeptanzkriterien
* Die bisherigen Analysen sind ohne die pyspark shell ausführbar
* Die Programme lassen sich mittels "phython <dateiname.py>" ausführen
* Spark wird bei der Ausführung des Programmes automatisch gestartet und im Anschluss wieder beendet

**Comment by LeaKleemann** [comment]
https://github.com/AtosReferenzApplikation/docker-container/wiki/Spark%3A-Eigenst%C3%A4ndig-laufbare-Programme
