### ISSUE TITLE
Einlesen der englischen Trainingsdaten

### ISSUE THREAD

**Issue by BenediktSt** [AtosReferenzApplikation/docker-container#74]
# Beschreibung
Als Analyst würde ich gerne die englischen Trainingsdaten samt Stimmungsbewertung einlesen, um die Sentimentanalyse zu verbessern.

# Akzeptanzkriterien
* Die Texte der Trainingsdaten können eingelesen werden
* Die Bewertungen der Trainingsdaten können eingelesen werden
* Die Bewertungen können noch eindeutig zu den Texten zugeordnet werden

**Comment by LeaKleemann** [comment]
https://github.com/AtosReferenzApplikation/feedback-data-analyzer/blob/lea/SentimentAnalysis/SentimentAnalysisML.py

**Comment by LeaKleemann** [comment]
https://github.com/AtosReferenzApplikation/docker-container/wiki/Spark%3A-Sentimentanalyse-mit-Logistic-Regression
