### ISSUE TITLE
Anhebung des Speicherlimits der Virtuellen Maschine dokumentieren

### ISSUE THREAD

**Issue by mtrenkle** [AtosReferenzApplikation/docker-container#78]
# Beschreibung
Hat der PC des Entwicklers mehr als 8GB RAM, sollte das Speicherlimit der Virtuellen Maschine angehoben werden. Dokumentation im Wiki

**Comment by MarvinK97** [comment]
[https://github.com/AtosReferenzApplikation/docker-container/wiki/Requirements](https://github.com/AtosReferenzApplikation/docker-container/wiki/Requirements)
