### ISSUE TITLE
Ausgehende Chatnachricht an den Kunden

### ISSUE THREAD

**Issue by mtrenkle** [AtosReferenzApplikation/docker-container#91]
# Beschreibung
Aus der Anwendung heraus soll dem Kunden eine Chatnachricht an die hinterlegte Adresse geschickt werden können.

# Akzeptanzkriterien
- Eine Nachricht kann im Chatfenster abgeschickt werden (neue Topic/neue Nachricht zur Topic)

**Comment by LucasG04** [comment]
Durch commit 497060434e4343e51a52c8e86b00cc1dacb4c7b7 erfüllt
